## Challenge: Reshape and Normalize a Matrix

### Reference
- This challenge exercise is based on:

### Key concepts
- Creating and ndarrays
- Using built-in functions to create ndarrays
- Accessing, deleting, and inserting elements into ndarrays


### Specific Skills and Knowlege
- Create array of zeros with desired shape
- Create array of ones 
- Create an array of constants
- Identity matrix
- Arrange function
- Linespace()
- Reshape()
- Random()

### Setup 

In [1]:
import numpy as np

### Challenge: Normalize and Reshape a Sequence

- A normalized matrix is a matrix where the values have been scaled to fall within a specific range — typically 0 to 1.
- This is commonly done to:
    - Make data easier to work with, especially for plotting or feeding into machine learning models.
    - Remove units or magnitude differences, so that comparisons are based on relative values.

### Real-World Scenario: Image Processing (Grayscale Images)

#### Situation:
- You're working with grayscale images, such as satellite photos, medical X-rays, or scanned documents.
- A grayscale image is often stored as a 2D matrix of pixel intensity values.
- These pixel values can range from 0 to 255 (in 8-bit images), but some image formats may use other ranges (e.g., 0–1023 or raw sensor data).

### Why Normalize?
Before you do any processing — like edge detection, noise filtering, or feeding the image into a machine learning model — you:

1. Normalize the matrix to range [0, 1]
This puts all pixel values on the same scale, regardless of the camera or sensor used.

2. Result:
- You get consistent behavior from your algorithms.
- You avoid numerical instability (especially in deep learning).
- You can compare multiple images or datasets fairly.



1. Create an array of numbers from 0 to 24.

2. Reshape it into a 5x5 matrix.

3. Normalize all values so they are between 0 and 1.

    Use the formula:

    ```
    ​normalized_matrix = (matrix - matrix.min()) / (matrix.max() - matrix.min())
    ```

In [2]:
# Step 1: Create an array from 0 to 24
arr = np.arange(25)

In [3]:
# Step 2: Reshape it into a 5x5 matrix
matrix = arr.reshape((5, 5))

In [4]:
# Step 3: Normalize the values to range 0 to 1
normalized_matrix = (matrix - matrix.min()) / (matrix.max() - matrix.min())

print("Original Matrix:\n", matrix)
print("\nNormalized Matrix:\n", normalized_matrix)

Original Matrix:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Normalized Matrix:
 [[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]
