# NumPy 1: 

# NumPy Intro

## References

https://numpy.org/devdocs/user/index.html

## Objectives

- How to import NumPy
- 
How to create multidimensional NumPy ndarrays using various methods- 
How to access and change elements in ndarray- s
How to load and save ndarra- ys
How to use slicing to select or change subsets of an ndar- ray
Understand the difference between a view and a copy of an nda- rray
How to use Boolean indexing and set operations to select or change subsets of an nd- array
How to sort nd- arrays
How to perform element-wise operations on n- darrays
Understand how NumPy uses broadcasting to perform operations on ndarrays of different sizes.

## Why use NumPy

### Speed:
- NumPy is significantly faster than Python lists for large array operations.
- Performance boost comes from memory-efficient array structures and optimized algorithms.

### Multidimensional Arrays:
- Supports vectors and matrices, which are essential in linear algebra and machine learning.
- Enables efficient matrix operations, useful in tasks like neural network training.

### Optimized Mathematical Functions:
- Includes a wide range of fast, built-in math functions.
- Reduces the need for complex loops, leading to cleaner, more readable code.

### Ecosystem and Popularity:

- Widely used in scientific computing with Python.
-Serves as the foundation for other libraries like Pandas.of NumPy.

### Example 1.a - Using a 1-D Array of Integers (Rank #1 Array)¶

## We import NumPy into Python

In [21]:
import numpy as np


### Example 1.a. We create a 1D ndarray that contains only integers

In [22]:

x = np.array([1, 2, 3, 4, 5, 100])
## Let's print the ndarray we just created using the print() command
print('x = ', x)


x =  [  1   2   3   4   5 100]


### Example 1.b - Using 1-D Array of Strings (Rank #1 Array)¶

In [23]:
# We create a rank 1 ndarray that only contains strings
x = np.array(['Hello', 'World'])

# We print information about x
print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  ['Hello' 'World']
x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U5


##  What if you mix the types of the array?

### My Example 1:  Mixed Type

In [24]:
# We create a rank 1 ndarray that only contains strings
x = np.array(['Hello', 'World', 100, 'Randall'])

# We print information about x
print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['Hello' 'World' '100' 'Randall']
x has dimensions: (4,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U21


### Example 1.c - Using a 1-D Array of Int and String (Rank #1 Array)

In [25]:
# We create a rank 1 ndarray from a Python list that contains integers and strings
x = np.array([1, 2, 'World'])

# We print information about x
print('x = ', x)
print('x has dimensions:', x.shape) 
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['1' '2' 'World']
x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U21


In [26]:
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int64
The elements in y are of type: float64
The elements in z are of type: float64


In [27]:
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

# We print the dtype x
print('x = ', x)
print('The elements in x are of type:', x.dtype)

x =  [1 2 3 4 5]
The elements in x are of type: int64


### Example 2 - Using a 2-D Array (Rank #2 Array)

In [28]:
# We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

# We print information about Y
print('Y = \n', Y)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')

Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64
Y has dimensions: (4, 3)
Y has a total of 12 elements


### Example 3 - Save the NumPy array to a File

In [29]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We save x into the current directory as 
np.save('my_array', x)

In [30]:
# We load the saved array from our current directory into variable y
y = np.load('my_array.npy')

# We print information about the ndarray we loaded
print('Y = \n', y)
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)

Y = 
 [1 2 3 4 5]
y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int64


# NumPy 2 Using Built-in Functions to Create ndarrays

In [31]:
my_list = [1,2,3,4,5]
np.array(my_list)

array([1, 2, 3, 4, 5])

### Built-in Functions
###### np.zeros()
###### np.ones()
###### np.full()
###### np.eye()
###### np.diag()
###### np.arrange()
###### np.linespace()
###### np.reshape()
###### np.random.random()
###### np.randomint()
###### np.randomnormal()

#### Example 1. Create a Numpy array of zeros with a desired shape

##### np.zeros()
- Creates an array filled with zeros. 

###### Syntax
```
np.zeros(shape, dtype=float)

```

###### Examples
```
import numpy as np

np.zeros(5)        
# Output: array([0., 0., 0., 0., 0.])

np.zeros((2, 3), dtype=in
#        [0,  0]]```)
e

```

In [32]:
# We create a 3 x 4 ndarray full of zeros. 
X = np.zeros((3,4), dtype=int)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

X has dimensions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


### Example 2. Create a Numpy array of ones
##### np.ones()
- Creates an array filled with ones. 

###### Syntax
```
np.ones(shape, dtype=float)

```

###### Examples
  
```np.ones(4)      
# Output: array([1., 1., 1., 1.])

np.ones((3, 2), dtype=int)  
# Output:
# array([[1, 1],
#        [1, 1],
#        [1, 1]])
e

```


In [33]:
# We create a 3 x 2 ndarray full of ones. 
X = np.ones((3,2))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype) 


X = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


### Example 3. Create a Numpy array of constants
##### np.full
Creates an array filled with a specified constant value.

###### Syntax
```
np.full(shape, fill_value, dtype=None) 
```
###### Example
```
np.full((2, 3), 7)  
# Output:
# array([[7, 7, 7],
#        [7, 7, 7]])

```


In [34]:
# We create a 2 x 3 ndarray full of fives.
X = np.full((2,3), 5) 

# We print X. We can print the array alone with print(X)
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[5 5 5]
 [5 5 5]]

X has dimensions: (2, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


In [35]:
# We create a 2 x 3 ndarray full of tens.
X = np.full((2,3), 5) 

# We print X. We can print the array alone with print(X)
print()
print(X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


[[5 5 5]
 [5 5 5]]

X has dimensions: (2, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


### Example 4. Create a Numpy array of Identity matrix
##### np.eye()
- Creates a 2D identity matrix (ones on the diagonal, zeros elsewhere). 

###### Syntax
```
np.eye(N, M=None, k=0, dtype=float)

```

###### Example 
```np.eye(3)    
# Output:
# array([[1., 0., 0.],
#        [0., 1., 0.],
#        [0., 0., 1.]])

np.eye(3, 4, k=1)  
# Output:
# array([[0., 1., 0., 0.],
#        [0., 0., 1., 0.],
#        [0., 0., 0., 1.]])
e

```

- If you multiply another matrix by it, nothing changes — just like how multiplying a number by 1 doesn’t change the number.
- Stabilizing models: It’s used to keep models from overfitting (memorizing too much) by adding a small amount of “balance.”
- Cleaning data: It shows up when we make data more uniform, like removing relationships between features.
- Neural networks: Helps pass data through a layer without changing it.
- Finding patterns: It helps when reducing dimensions to find the most important parts of the data (like in PCA).

In [36]:
# We create a 5 x 5 Identity matrix. 
X = np.eye(5)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)  


X = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

X has dimensions: (5, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


### Example 5. Create a Numpy array of constants
##### np.diag()
- If given a 1D array, returns a 2D diagonal matrix with that array on the diagonal.
- If given a 2D array, returns the diagonal elements.

###### Syntax
```
np.diag(v, k=0)


```

###### Example 
```# From 1D array to diagonal matrix
np.diag([1, 2, 3])  
# Output:
# array([[1, 0, 0],
#        [0, 2, 0],
#        [0, 0, 3]])

# From 2D array to 1D diagonal
np.diag(np.array([[1, 2], [3, 4]]))  
# Output: arra([1, 4])
0, 1.]])
e

``` 4])
0, 1.]])
e

In [37]:
# Create a 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50
# on its main diagonal
X = np.diag([10,20,30,50])

# We print X
print()
print('X = \n', X)
print()


X = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]

