# NumPy 2 Using Built-in Functions to Create ndarrays

#### Setup

In [41]:
import numpy as np

### Example 6. Create a Numpy array of evenly spaced values in a given range, using arange(stop_val)

#####  np.arrange()
Creates an array of evenly spaced values within a specified range (similar to Python’s built-in range() but returns a NumPy array).

###### Syntax
```
np.arange([start,] stop[, step], dtype=None)

```

###### Example
```import numpy as np

np.arange(5)      
# Output: array([0, 1, 2, 3, 4])

np.arange(2, 10)  
# Output: array([2, 3, 4, 5, 6, 7, 8, 9])

np.arange(1, 10, 2)  
# Output: array([1, 3, 5, 7, 9])

np.arange(0, 1, 0.2)  
# Output: array([0. , 0.2, 0.4, 0.6, 0.8])


```

In [42]:
# We create a rank 1 ndarray that has sequential integers from 0 to 9
x = np.arange(10)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x =  [0 1 2 3 4 5 6 7 8 9]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


### Example 7. Create a Numpy array using arange(start_val, stop_val)

In [43]:
# We create a rank 1 ndarray that has sequential integers from 4 to 9. 
x = np.arange(4,10)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x =  [4 5 6 7 8 9]

x has dimensions: (6,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


In [44]:
# Another example
x = np.arange(50,100)
y = np.arange(50,100, 10)

# We print the ndarray
print()
print(x)
print()
print(y)
print()



[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]

[50 60 70 80 90]



### Example 8. Create a Numpy array using arange(start_val, stop_val, step_size)

In [45]:
# We create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
x = np.arange(1,14,3)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x =  [ 1  4  7 10 13]

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


### Example 9. Create a Numpy array using linspace(start, stop, n), with stop inclusive.

##### linespace()
- Creates an array of evenly spaced numbers over a specified interval, including both the start and stop values.

###### Syntax

```
np.linspace(start, stop, num=50, endpoint=True, retstep=False)

```

###### Examples
  
```
import numpy as np

np.linspace(0, 1, 5)  
# Output: array([0.  , 0.25, 0.5 , 0.75, 1.  ])

np.linspace(0, 1, 5, retstep=True)  
# Output: (array([0.  , 0.25, 0.5 , 0.75, 1.  ]), 0.25)

```

In [46]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25.
x = np.linspace(0,25,10)

# We print the ndarray
print()
print('x = \n', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x = 
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


#### Mini Challenge:  Try different arguments for linespace()

In [47]:
# Experiment
x = np.linspace(0,10,15)

# We print the ndarray
print()
print('x = \n', x)
print()


x = 
 [ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]



### Example 10. Create a Numpy array using linspace(start, stop, n), with stop excluded.
- When the endpoint is included, then the spacing is around 2.8, but now it's 2.5 since we have fewer.

In [48]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25,
# with 25 excluded.
x = np.linspace(0,25,10, endpoint = False)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


### Example 11. Create a Numpy array by feeding the output of arange() function to the reshape() function.

In [49]:
# We create a rank 1 ndarray with sequential integers from 0 to 19
x = np.arange(20)

# We print x
print()
print('Original x = ', x)
print()

# We reshape x into a 4 x 5 ndarray 
x = np.reshape(x, (4,5))

# We print the reshaped x
print()
print('Reshaped x = \n', x)
print()

# We print information about the reshaped x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


Original x =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Reshaped x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

x has dimensions: (4, 5)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


#### But it has to go in evenly (Uncomment when want to see error)

In [50]:
# We create a rank 1 ndarray with sequential integers from 0 to 19
# We have 20 values.
# In the original example, 4 x 5 = 20
x = np.arange(20)

# We print x
print()
print('Original x = \n', x)
print()

# TODO:  Uncomment this line to see the error
# We reshape x into a 4 x 5 ndarray 
# x = np.reshape(x, (4,6))

# We print the reshaped x
print()
print('Reshaped x = \n', x)
print()



Original x = 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Reshaped x = 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]



### Example 12. Create a Numpy array by calling the reshape() function from the output of arange() function.

##### arrange()
Creates an array with evenly spaced values within a given range.

###### Syntax  

```
np.arange([start,] stop[, step])

```
###### Example   
```
import numpy as np

np.arange(0, 10, 2)  # Output: array([0, 2, 4, 6, 8])

```

##### reshape()
Changes the shape of an existing array without changing its data.

###### Syntax  
```
array.reshape(new_shape)
```

###### Example 
```
a = np.arange(6)          # array([0, 1, 2, 3, 4, 5])
a.reshape((2, 3))         # Output: array([[0, 1, 2],
                          #                 [3, 4, 5])

```


#### Before

In [51]:
Y = np.arange(20)
print('Y = \n', Y)

Y = 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


#### After

In [52]:
# We create a a rank 1 ndarray with sequential integers from 0 to 19 and
# reshape it to a 4 x 5 array 
Y = np.arange(20).reshape(4, 5)

# We print Y
print()
print('Y = \n', Y)
print()

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype) 


Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Y has dimensions: (4, 5)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


### Example 13. Create a rank 2 Numpy array by using the reshape() function.

##### linespace()
- Creates an array of evenly spaced numbers over a specified interval, including both the start and stop values.

###### Syntax

```
np.linspace(start, stop, num=50, endpoint=True, retstep=False)

```
######  Examples
  
```
import numpy as np

np.linspace(0, 1, 5)  
# Output: array([0.  , 0.25, 0.5 , 0.75, 1.  
np.linspace(0, 1, 5, retstep=True)  
# Output: (array([0.  , 0.25, 0.5 , 0.75, 1.  ]), 0.25)
])

```
    
##### reshape()
- Changes the shape of an existing array without changing its data.

```
code
```

#### Before

In [53]:
X = np.linspace(0,50,10, endpoint=False)
print()
print('X = \n', X)
print()


X = 
 [ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45.]



#### After

In [54]:
# We create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50,
# with 50 excluded. We then reshape it to a 5 x 2 ndarray
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]

X has dimensions: (5, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


### Example 14. Create a Numpy array using the numpy.random.random() function.

##### random.random()
- Generates random floating-point numbers between 0.0 and 1.0 (exclusive of 1.0).

###### Syntax
```
numpy.random.random(size=None)
```


###### Example
``` 
import numpy as np

np.random.random()         
# Output: 0.5488135 (example — a single random float between 0 and 1)

np.random.random(5)        
# Output: array([0.42, 0.64, 0.13, 0.89, 0.37]) — 1D array of 5 random values

np.random.random((2, 3))   
# Output: 2x3 array of random valof 1.0).

In [55]:
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
X = np.random.random((3,3))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)


X = 
 [[0.08530466 0.75891568 0.07281223]
 [0.16474008 0.80287017 0.86891787]
 [0.37065498 0.55501924 0.70615207]]

X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


### Example 15. Create a Numpy array using the numpy.random.randint() function.

##### random.randint()
- Generates random integers from a specified range.

###### Syntax

```numpy.random.randint(low, high=None, size=None, dtype=int)```

###### Example

```import numpy as np

np.random.randint(5)       
# Output: Random int from 0 to 4

np.random.randint(10, 20)  
# Output: Random int from 10 to 19

np.random.randint(1, 100, size=5)    
# Output: array of 5 random integers between 1 and 99

np.random.randint(0, 10, size=(2, 3)) 
# Output: 2x3 array of random ints ```from 0 to 9



In [56]:
# We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).
X = np.random.randint(4,15,size=(3,2))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[ 6  5]
 [13  9]
 [12 12]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


### Example 16. Create a Numpy array of "Normal" distributed random numbers, using the numpy.random.normal() function.

##### random.normal()
##### 
- Generates random numbers drawn from a normal (Gaussian) distribution.

###### Syntax
```
numpy.random.normal(loc=0.0, scale=1.0, size=None)
```

###### Example
```
import numpy as np

np.random.normal()  
# Output: single value from standard normal distribution (mean=0, std=1)

np.random.normal(loc=10, scale=2, size=5)  
# Output: array of 5 values with mean=10 and std=2

np.random.normal(0, 1, (2, 3))  
# Output: 2x3 array of values from standard normal distribution

```

In [57]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
X = np.random.normal(0, 0.1, size=(1000,1000))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')


X = 
 [[-0.11586422 -0.00624689 -0.08087663 ...  0.14708919 -0.04952362
  -0.00208334]
 [-0.00508295 -0.04249468 -0.11955033 ... -0.27009056 -0.17814803
   0.0141583 ]
 [-0.11107488 -0.09984679 -0.11044602 ...  0.18585227  0.09246987
  -0.13722204]
 ...
 [ 0.03654076 -0.07512042  0.03042401 ... -0.17699001  0.04042948
   0.00541405]
 [ 0.05369216 -0.10825608  0.06453404 ...  0.00138573  0.14615659
  -0.13876991]
 [-0.18536186  0.06623914 -0.06537965 ...  0.00206676 -0.03898145
  -0.049776  ]]

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: -4.237220233678941e-05
The maximum value in X is: 0.4668566962346485
The minimum value in X is: -0.5486229332616123
X has 500442 negative numbers
X has 499558 positive numbers
